export { doComplete, resolveCompletionItem, completionsFromClassList } from './completionProvider'
export { doValidate } from './diagnostics/diagnosticsProvider'
export { doHover } from './hoverProvider'
export { doCodeActions } from './codeActions/codeActionProvider'
export { getDocumentColors } from './documentColorProvider'
export { getDocumentLinks } from './documentLinksProvider'
export { getCodeLens } from './codeLensProvider'
export { type Feature, supportedFeatures } from './features'
export * from './util/state'
export * from './diagnostics/types'
export * from './util/color'
