name: Run Tests
on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22, 24]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    name: Run Tests - Node v${{ matrix.node }} / ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: |
          cd packages/tailwindcss-language-server &&
          pnpm run build &&
          pnpm run test
