name: Run Tests
on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22, 23]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    name: Run Tests - Node v${{ matrix.node }} / ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install

      - name: Run service tests
        working-directory: packages/tailwindcss-language-service
        run: pnpm run build && pnpm run test

      - name: Run server tests
        working-directory: packages/tailwindcss-language-server
        run: |
          pnpm run build && pnpm run test
