name: Publish Release
concurrency: publish
on:
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3
        with:
          version: ^9.6.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: >
          cd packages/tailwindcss-language-server &&
          pnpm run build &&
          pnpm run test
      - name: Publish IntelliSense
        env:
          VSCODE_TOKEN: ${{ secrets.VSCODE_TOKEN }}
        run: >
          cd packages/vscode-tailwindcss &&
          pnpm run publish -p $VSCODE_TOKEN
